### ISSUE TITLE
Append the JS code at the end of piwik.js

### ISSUE THREAD

**Issue by mattab** [innocraft/plugin-JsTrackerCustom#2]
Currently the JS code may be written in the middle of piwik.js before other plugins' JS code.
Sometimes the customisations to the JS code rely on the other plugin's code, so the customisations done by JsTrackerCustom should appear at the end of piwik.js

**Comment by sgiehl** [comment]
That's not doable without changes in core.

**Comment by mattab** [comment]
thought maybe it could work with `'after' => true` in the event listener, but maybe not?

**Comment by sgiehl** [comment]
the plugin does not use any event listener. Matomo automatically includes the `tracker.js` that is created by the plugin. The files to be included are looked up using a `glob` in core, so the order is defined by that result I guess.
